meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  padding: 2
  px: kx+padding
  py: ky+padding
  dpx: kx + 8
  dpy: ky + 8
  scrollwheel_width: 17
  scrollwheel_height: 14
  encoder_width: 14
  encoder_height: 13.2
  mcu_height: 34
  mcu_width: 18
  mcu_padding: 1.5
  switchplate_switch_cutout: 14
  switchplate_scrollwheel_cutout_x: 18
  switchplate_scrollwheel_cutout_y: 15
  switchplate_encoder_cutout_x: 14.5
  switchplate_encoder_cutout_y: 13.5
points:
  mirror: &mirror
    ref: matrix_inner_num
    distance: 5kx
  zones:
    matrix:
      anchor.shift: [50, -150]
      columns:
        outer:
          rows:
            mod.skip: true
          key:
            column_net: col0
        pinky:
          rows:
            mod.skip: true
          key:
            origin: [0, 8]
            column_net: col1
        ring:
          key:
            origin: [0, 8]
            stagger: 2.5
            column_net: col2
          rows.mod.skip: true
        middle:
          key:
            stagger: 3
            column_net: col3
          rows:
            mod:
              column_net: col3
            mod.skip: true
        index:
          key:
            stagger: -2.5
            column_net: col4
          rows:
            mod:
              column_net: col4
            mod.skip: true
        inner:
          rows:
            mod.skip: true
          key:
              stagger: -2.5
              column_net: col5
      rows:
        mod:
          row_net: row4
          tags: [switch_thumb]
        bottom:
          row_net: row3
          tags: [switch_top]
        home:
          row_net: row2
          tags: [switch_top]
        top:
          row_net: row1
          tags: [switch_top]
        num:
          row_net: row0
          tags: [switch_bottom]
    thumbs:
      key:
        tags: [switch]
      anchor:
        ref: matrix_index_bottom
        shift: [-30, -23]
      columns:
        inner:
          key:
            row_net: row4
            column_net: col2
            shift: [3,0.0]
        home:
          key:
            row_net: row4
            column_net: col3
            shift: [4,0]
            stagger: 1
        layer:
          key:
            spread: 22
            splay: -10
            stagger: -2.5
            shift: [3,0]
            row_net: row4 
            column_net: col4
        space:
          key:
            spread: 36
            splay: -15
            stagger: -2
            width: 1kx
            row_net: row4
            shift: [,0]
            column_net: col5
      rows:
        cluster:
    scrollwheel:
      anchor:
        ref: matrix_inner_bottom
      columns:
        scrollwheel:
          key:
            tags: [scrollwheel]
            column_net: col5
            width: scrollwheel_width
            height: scrollwheel_height
            name: scrollwheel
            shift: [22.5,2] 
      rows:
        enc:
          row_net: row2
    encoder:
      anchor:
        ref: matrix_inner_bottom
      columns:
        encoder:
          key:
            tags: [encoder]
            column_net: col5
            shift: [22.5,2]
            name: encoder
            width: encoder_width
            height: encoder_height
      rows:
        enc:
          row_net: row2
    mcu:
      anchor:
        ref: matrix_inner_num
      columns:
        mcu:
          key:
            tags: [mcu]
            width: mcu_height
            height: mcu_width
            rotate: -90
            shift: [22.5, -8]
outlines:
  board_outline:
    - what: polygon
      fillet: 0.99
      points:
        - ref: matrix_outer_num
          shift: [0.5kx, 0.5ky]
        - ref: matrix_ou 

  switchplate_base:
    - what: polygon
      fillet: 0.99
      points:
        - ref: matrix_outer_num
          shift: [-kx/2-1, ky/2+1.25]
        - ref: matrix_outer_num
          shift: [kx/2-1, ky/2+1.25] 

        - ref: matrix_pinky_num
          shift: [-kx/2-1, ky/2+1.25]
        - ref: matrix_pinky_num
          shift: [+kx/2-1, ky/2+1.25]

        - ref: matrix_ring_num
          shift: [-kx/2-1, ky/2+1.5]
        - ref: matrix_ring_num
          shift: [+kx/2-1, ky/2+1.5]

        - ref: matrix_middle_num
          shift: [-kx/2-1, ky/2+2]
        - ref: matrix_middle_num
          shift: [+kx/2+1, ky/2+2]

        - ref: matrix_index_num
          shift: [-kx/2+1, ky/2+1.25]
        - ref: matrix_index_num
          shift: [+kx/2+1, ky/2+1.25]

        - ref: matrix_inner_num
          shift: [-kx/2+1, ky/2]
        - ref: matrix_inner_num
          shift: [+kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2]
        - ref: matrix_inner_home
          shift: [-kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2]
        - ref: matrix_inner_home
          shift: [kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2-2]
        - ref: matrix_inner_bottom
          shift: [kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2-1]
        - ref: matrix_inner_bottom
          shift: [kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2-1]

        - ref: thumbs_space_cluster
          shift: [kx/2+1, -ky/2-1]
        - ref: thumbs_space_cluster
          shift: [-kx/2-1, -ky/2-1]
        - ref: thumbs_layer_cluster
          shift: [kx/2-1, -ky/2-2]
        - ref: thumbs_layer_cluster
          shift: [-kx/2-1, -ky/2-1]
        - ref: thumbs_home_cluster
          shift: [-kx/2+1, -ky/2-2]
        - ref: thumbs_home_cluster
          shift: [-kx/2+1, -ky/2-2]
        - ref: thumbs_inner_cluster
          shift: [-kx/2-2, -ky/2-1]
        - ref: thumbs_inner_cluster
          shift: [-kx/2-2, -ky/2-1]
        - ref: matrix_pinky_bottom
          shift: [kx/4, -ky/2-1]
        - ref: matrix_outer_bottom
          shift: [-kx/2-1, -ky/2-1]

  switch_cutout:
    - what: rectangle
      where: [/^matrix_.*/,/^thumbs_.*/]
      size: switchplate_switch_cutout
      bound: false
  encoder_cutout:
    - what: rectangle
      where: [encoder]
      size: [switchplate_scrollwheel_cutout_x, switchplate_scrollwheel_cutout_y]
      bound: false
  scroll_cutout:
    - what: rectangle
      where: thumbs_inner_cluster
      size: [switchplate_scrollwheel_cutout_x, switchplate_scrollwheel_cutout_y]
      bound: false
      adjust:
        shift: [-2,0]
  screen_cutout:
    - what: rectangle
      where: [mcu]
      size: [45, 21]
      fillet: 2
      bound: 
  switchplate:
    - what: outline
      name: switchplate_base
    - what: outline
      name: switch_cutout
      operation: subtract
    - what: outline
      name: encoder_cutout
      operation: subtract
    - what: outline
      name: screen_cutout
      operation: subtract
    - what: outline
      name: scroll_cutout
      operation: subtract

