meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  padding: 2
  px: kx+padding
  py: ky+padding
  dpx: kx + 8
  dpy: ky + 8
  scrollwheel_width: 17
  scrollwheel_height: 14
  mcu_height: 34
  mcu_width: 18
  mcu_padding: 1.5
  switchplate_switch_cutout: 14
  switchplate_scrollwheel_cutout_x: 17.5
  switchplate_scrollwheel_cutout_y: 14.5
points:
  mirror: &mirror
    ref: matrix_inner_num
    distance: 5kx
  zones:
    matrix:
      columns:
        outer:
          rows:
            mod.skip: true
          key:
            column_net: row0
        pinky:
          rows:
            mod.skip: true
          key:
            origin: [0, 8]
            column_net: row1
        ring:
          key:
            origin: [0, 8]
            stagger: 1
            column_net: row2
          rows.mod.skip: true
        middle:
          key:
            stagger: 1.5
            column_net: row3
          rows:
            mod:
              column_net: row1
            mod.skip: true
        index:
          key:
            stagger: -2.5
            column_net: row4
          rows:
            mod:
              column_net: row2
            mod.skip: true
        inner:
          rows:
            mod.skip: true
          key:
              stagger: -2.5
              column_net: row5
      rows:
        mod:
          row_net: col4
          tags: [switch_thumb]
        bottom:
          row_net: col3
          tags: [switch_top]
        home:
          row_net: col2
          tags: [switch_top]
        top:
          row_net: col1
          tags: [switch_top]
        num:
          row_net: col0
          tags: [switch_bottom]
    thumbs:
      key:
        tags: [switch]
      anchor:
        ref: matrix_inner_mod
        shift: [-53,0]
      columns:
        inner:
          key:
            row_net: row4
            column_net: col2
            shift: [1,2]
        home:
          key:
            row_net: row4
            column_net: col3
            shift: [3,1]
        layer:
          key:
            row_net: row4
            column_net: col4
            splay: -10
            shift: [5,-1]
        space:
          key:
            width: 1.5kx
            row_net: row4
            column_net: col5
            splay: 80
            shift: [10,-10]
      rows:
        cluster:
    scrollwheel:
      anchor:
        ref: matrix_inner_home
      columns:
        scrollwheel:
          key:
            tags: [scrollwheel]
            column_net: col5
            width: scrollwheel_width
            height: scrollwheel_height
            name: scrollwheel
            shift: [20,-5]
      rows:
        scrollwheel:
          row_net: row4
    encoder:
      anchor:
        ref: matrix_inner_mod
        shift: [-53,0]
      columns:
        inner:
          key:
            tags: [encoder]
            row_net: row4
            column_net: col2
            shift: [1,2]
            name: encoder
      rows:
        cluster:
    mcu:
      anchor:
        ref: matrix_inner_num
      columns:
        mcu:
          key:
            tags: [mcu]
            width: mcu_height
            height: mcu_width
            rotate: -90
            shift: [kx+mcu_padding, -mcu_width/2-0.3]
outlines:
  board_outline:
    - what: polygon
      points:
        - ref: matrix_outer_num
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_num
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_num
          shift: [-0.5px,0.65py]
        - ref: matrix_inner_num
          shift: [0.5px+mcu_padding+mcu_width+0.25,0.5py]
        - ref: matrix_inner_home
          shift: [0.5px+mcu_padding+mcu_width+0.25,-0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_home_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.5px,-0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px,-0.5py]
  switchplate_base:
    - what: polygon
      points:
        - ref: matrix_outer_num
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_num
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_index_num
          shift: [-0.5px,0.65py]
        - ref: matrix_inner_num
          shift: [0.5px+mcu_padding+mcu_width+0.25,0.5py]
        - ref: matrix_inner_home
          shift: [0.5px+mcu_padding+mcu_width+0.25,-0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_home_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.5px,-0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px,-0.5py]
  switch_cutout:
    - what: rectangle
      where: [/^matrix_.*/,/^thumbs_.*/]
      size: switchplate_switch_cutout
      bound: false
  scrollwheel_cutout:
    - what: rectangle
      where: [scrollwheel]
      size: [switchplate_scrollwheel_cutout_x, switchplate_scrollwheel_cutout_y]
      bound: false
  screen_cutout:
    - what: rectangle
      where: [mcu]
      size: [45, 21]
      bound: false
  switchplate:
    - what: outline
      name: switchplate_base
    - what: outline
      name: switch_cutout
      operation: subtract
    - what: outline
      name: scrollwheel_cutout
      operation: subtract
    - what: outline
      name: screen_cutout
      operation: subtract
pcbs:
  left:
    outlines.main.outline: board_outline
    footprints:
      gateron_hotswap:
        what: ceoloide/switch_gateron_ks27_ks33
        where: [/^matrix_.*/,/^thumbs_.*/]
        params:
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode_main:
        what: ceoloide/diode_tht_sod123
        where: /^matrix_(?!(?:mod|bottom|home|top|num))./
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 0
          shift: [1,9]
      diode_thumb:
        what: ceoloide/diode_tht_sod123
        where: /^thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 0
          shift: [1,9]
      scrollwheel:
        what: scrollwheel
        where:
          ref: scrollwheel
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          A: undef
          B: GND
          C: ENCA
          D: ENCB
      scroll_diode:
        what: ceoloide/diode_tht_sod123
        where:
          ref: matrix_inner_home
          shift: [20, -11]
        params: 
          from: "{{colrow}}"
          to: "{{row_net}}"
      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
          ref: encoder
      controller:
        what: ceoloide/mcu_supermini_nrf52840
        where: 
          ref: matrix_inner_num
          shift: [20,-8]
        adjust:
          rotate: 0
        params:
          RAW: BAT_RAW
          GND: GND
          RST: RST
          VCC: VCC
          P21: ENCA
          P20: ENCB
          P19: row0
          P18: row1
          P15: row2
          P14: row3
          P16: row4
          P10: row5
          P1: BAT_GND
          P0: P0
          P2: SDA
          P3: SCL
          P4: CS
          P5: col0
          P6: col1
          P7: col2
          P8: col3
          P9: col4
          reverse_mount: true
      niceview:
        what: ceoloide/display_nice_view
        where: 
          ref: matrix_inner_num
          shift: [20,-10]
        params:
          VCC: VCC
          GND: GND
          CS: CS
          SCK: SCL
          MOSI: SDA
      slider:
        what: ceoloide/power_switch_smd_side 
        where: 
          ref: matrix_inner_home
          shift: [28,-17]
        params:
          side: F
          from: ON_P
          to: BAT_RAW
          invert_behavior: false
      battery:
        what: ceoloide/battery_connector_molex_pico_ezmate_1x02
        where: 
          ref: matrix_inner_num
          shift: [20,0]
        params:
          reversible: true
          BAT_P: BAT_GND
          BAT_N: ON_P
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where: 
          ref: matrix_inner_home
          shift: [28.5, 9.5]
          rotate: 270
        params:
          include_bosses: true
          from: RST
          to: GND
      left_text:
        what: ceoloide/utility_text
        where:
          ref: matrix_inner_top
          shift: [20,5]
        params:
          text: "Left"
          thickness: 1
          knockout: true
          width: 2
          height: 2 
        
cases:
