

meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  padding: 2
  px: kx+padding
  py: ky+padding
  dpx: kx + 8
  dpy: ky + 8
  scrollwheel_width: 17
  scrollwheel_height: 14
  encoder_width: 14
  encoder_height: 13.2
  mcu_height: 34
  mcu_width: 18
  mcu_padding: 1.5
  switchplate_switch_cutout: 14
  switchplate_scrollwheel_cutout_x: 18
  switchplate_scrollwheel_cutout_y: 15
  switchplate_encoder_cutout_x: 14.5
  switchplate_encoder_cutout_y: 13.5
points:
  mirror: &mirror
    ref: matrix_inner_num
    distance: 5kx
  zones:
    matrix:
      anchor.shift: [50, -150]
      columns:
        outer:
          rows:
            mod.skip: true
          key:
            column_net: col0
        pinky:
          rows:
            mod.skip: true
          key:
            origin: [0, 8]
            column_net: col1
        ring:
          key:
            origin: [0, 8]
            stagger: 2.5
            column_net: col2
          rows.mod.skip: true
        middle:
          key:
            stagger: 3
            column_net: col3
          rows:
            mod:
              column_net: col3
            mod.skip: true
        index:
          key:
            stagger: -2.5
            column_net: col4
          rows:
            mod:
              column_net: col4
            mod.skip: true
        inner:
          rows:
            mod.skip: true
          key:
              stagger: -2.5
              column_net: col5
      rows:
        mod:
          row_net: row4
          tags: [switch_thumb]
        bottom:
          row_net: row3
          tags: [switch_top]
        home:
          row_net: row2
          tags: [switch_top]
        top:
          row_net: row1
          tags: [switch_top]
        num:
          row_net: row0
          tags: [switch_bottom]
    thumbs:
      key:
        tags: [switch]
      anchor:
        ref: matrix_index_bottom
        shift: [-30, -20]
      columns:
        inner:
          key:
            row_net: row4
            column_net: col2
            shift: [2,0.0]
        home:
          key:
            row_net: row4
            column_net: col3
            shift: [2,0]
            stagger: 1
        layer:
          key:
            spread: 22
            splay: -5
            stagger: -2.5
            shift: [0,0]
            row_net: row4 
            column_net: col4
        space:
          key:
            spread: 34
            splay: 65
            stagger:  0
            width: 1.5kx
            row_net: row4
            shift: [,10.5]
            column_net: col5
      rows:
        cluster:
    scrollwheel:
      anchor:
        ref: matrix_inner_home
      columns:
        scrollwheel:
          key:
            tags: [scrollwheel]
            column_net: col5
            width: scrollwheel_width
            height: scrollwheel_height
            name: scrollwheel
            shift: [22.5,-2.5] 
      rows:
        enc:
          row_net: row2
    encoder:
      anchor:
        ref: matrix_inner_home
      columns:
        encoder:
          key:
            tags: [encoder]
            column_net: col5
            shift: [22.5,-3]
            name: encoder
            width: encoder_width
            height: encoder_height
      rows:
        enc:
          row_net: row2
    mcu:
      anchor:
        ref: matrix_inner_num
      columns:
        mcu:
          key:
            tags: [mcu]
            width: mcu_height
            height: mcu_width
            rotate: -90
            shift: [22.5, -8]
outlines:
  board_outline:
    - what: polygon
      fillet: 0.99
      points:
        - ref: matrix_outer_num
          shift: [-kx/2-1, ky/2+1.25]
        - ref: matrix_outer_num
          shift: [kx/2-1, ky/2+1.25] 

        - ref: matrix_pinky_num
          shift: [-kx/2-1, ky/2+1.25]
        - ref: matrix_pinky_num
          shift: [+kx/2-1, ky/2+1.25]

        - ref: matrix_ring_num
          shift: [-kx/2-1, ky/2+1.5]
        - ref: matrix_ring_num
          shift: [+kx/2-1, ky/2+1.5]

        - ref: matrix_middle_num
          shift: [-kx/2-1, ky/2+2]
        - ref: matrix_middle_num
          shift: [+kx/2+1, ky/2+2]

        - ref: matrix_index_num
          shift: [-kx/2+1, ky/2+1.25]
        - ref: matrix_index_num
          shift: [+kx/2+1, ky/2+1.25]

        - ref: matrix_inner_num
          shift: [-kx/2+1, ky/2]
        - ref: matrix_inner_num
          shift: [+kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2]
        - ref: matrix_inner_home
          shift: [+kx/2+2+mcu_padding+mcu_width+0.25+2  , ky/2]
        - ref: matrix_inner_home
          shift: [+kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2-5]

        - ref: thumbs_space_cluster
          shift: [kx/2+1, -ky/2-2]
        - ref: thumbs_space_cluster
          shift: [-kx/2-3, -ky/2-2]
        - ref: thumbs_layer_cluster
          shift: [kx/2-1, -ky/2-2]
        - ref: thumbs_layer_cluster
          shift: [kx/2-1, -ky/2-2]
        - ref: thumbs_home_cluster
          shift: [-kx/2+1, -ky/2-2]
        - ref: thumbs_home_cluster
          shift: [-kx/2+1, -ky/2-2]
        - ref: thumbs_inner_cluster
          shift: [kx/2-2, -ky/2-1]
        - ref: thumbs_inner_cluster
          shift: [-kx/2-2, -ky/2-1]
        - ref: matrix_pinky_bottom
          shift: [kx/2-1, -ky/2-1]
        - ref: matrix_pinky_bottom
          shift: [-kx/2-1, -ky/2-1]
        - ref: matrix_outer_bottom
          shift: [kx/2+1, -ky/2-1]
        - ref: matrix_outer_bottom
          shift: [-kx/2-1, -ky/2-1]

  switchplate_base:
    - what: polygon
      fillet: 0.99
      points:
        - ref: matrix_outer_num
          shift: [-kx/2-1, ky/2+1.25]
        - ref: matrix_outer_num
          shift: [kx/2-1, ky/2+1.25] 

        - ref: matrix_pinky_num
          shift: [-kx/2-1, ky/2+1.25]
        - ref: matrix_pinky_num
          shift: [+kx/2-1, ky/2+1.25]

        - ref: matrix_ring_num
          shift: [-kx/2-1, ky/2+1.5]
        - ref: matrix_ring_num
          shift: [+kx/2-1, ky/2+1.5]

        - ref: matrix_middle_num
          shift: [-kx/2-1, ky/2+2]
        - ref: matrix_middle_num
          shift: [+kx/2+1, ky/2+2]

        - ref: matrix_index_num
          shift: [-kx/2+1, ky/2+1.25]
        - ref: matrix_index_num
          shift: [+kx/2+1, ky/2+1.25]

        - ref: matrix_inner_num
          shift: [-kx/2+1, ky/2]
        - ref: matrix_inner_num
          shift: [+kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2]
        - ref: matrix_inner_home
          shift: [-kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2]
        - ref: matrix_inner_home
          shift: [+kx/2+2+mcu_padding+mcu_width+0.25+2, ky/2-2.3]

        - ref: thumbs_space_cluster
          shift: [kx/2+1, -ky/2-2]
        - ref: thumbs_space_cluster
          shift: [-kx/2-3, -ky/2-2]
        - ref: thumbs_layer_cluster
          shift: [kx/2-1, -ky/2-2]
        - ref: thumbs_layer_cluster
          shift: [kx/2-1, -ky/2-2]
        - ref: thumbs_home_cluster
          shift: [-kx/2+1, -ky/2-3]
        - ref: thumbs_home_cluster
          shift: [-kx/2+1, -ky/2-3]
        - ref: thumbs_inner_cluster
          shift: [kx/2-2, -ky/2-2]
        - ref: thumbs_inner_cluster
          shift: [-kx/2-2, -ky/2-2]
        - ref: matrix_pinky_bottom
          shift: [kx/2-1, -ky/2-1]
        - ref: matrix_pinky_bottom
          shift: [-kx/2-1, -ky/2-1]
        - ref: matrix_outer_bottom
          shift: [kx/2+1, -ky/2-1]
        - ref: matrix_outer_bottom
          shift: [-kx/2-1, -ky/2-1]

  switch_cutout:
    - what: rectangle
      where: [/^matrix_.*/,/^thumbs_.*/]
      size: switchplate_switch_cutout
      bound: false
  encoder_cutout:
    - what: rectangle
      where: [encoder]
      size: [switchplate_scrollwheel_cutout_x, switchplate_scrollwheel_cutout_y]
      bound: false
  scroll_cutout:
    - what: rectangle
      where: thumbs_inner_cluster
      size: [switchplate_scrollwheel_cutout_x, switchplate_scrollwheel_cutout_y]
      bound: false
      adjust:
        shift: [-2,0]
  screen_cutout:
    - what: rectangle
      where: [mcu]
      size: [45, 21]
      fillet: 2
      bound: 
  switchplate:
    - what: outline
      name: switchplate_base
    - what: outline
      name: switch_cutout
      operation: subtract
    - what: outline
      name: encoder_cutout
      operation: subtract
    - what: outline
      name: screen_cutout
      operation: subtract
    - what: outline
      name: scroll_cutout
      operation: subtract
pcbs:
  left:
    template: kicad8
    outlines.main.outline: board_outline
    footprints:
      gateron_hotswap:
        what: switch_gateron_ks27_ks33
        where: [/^matrix_.*/,/^thumbs_.*/]
        params:
          include_socket_silks: true
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode_main:
        what: diode_tht_sod123
        where: /^matrix_(?!(?:mod|bottom|home|top|num))./
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 0
          shift: [0,-6]
      diode_thumb:
        what: diode_tht_sod123
        where: /^thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 0
          shift: [1,10]
      scroll_diode:
        what: diode_tht_sod123
        where:
          ref: scrollwheel
          shift: [0, 8]
        params: 
          from: "{{colrow}}"
          to: "{{row_net}}"
      encoder:
        what: rotary_encoder_ec11_ec12
        where:
          ref: encoder
        params:
          S1: "{{column_net}}"
          S2: scrollwheel_enc
          A: ENCA
          B: GND
          C: ENCB
        adjust:
          rotate: 270
          shift: [-0.5,0]
      encoder2:
        what: rotary_encoder_ec11_ec12
        where:
          ref: thumbs_inner_cluster
        params:
          S1: "{{column_net}}"
          S2: "{{colrow}}"
          A: ENCC
          B: GND
          C: ENCD
        adjust:
          rotate: 0
          shift: [0,1.2]
      controller:
        what: mcu_supermini_nrf52840
        where: 
          ref: matrix_inner_num
          shift: [22.5,-8]
        adjust:
          rotate: 0
        params:
          RAW: BAT_RAW
          GND: GND
          RST: RST
          VCC: VCC
          P21: ENCA
          P20: ENCB
          P19: row0
          P18: row1
          P15: row2
          P14: row3
          P16: row4
          P10: row5
          P1: BAT_GND
          P0: P0
          P2: SDA
          P3: SCL
          P4: CS
          P5: col0
          P6: col1
          P7: col2
          P8: col3
          P9: col4
          P101: ENCC
          P102: ENCD
          reverse_mount: true
          include_extra_pins: true
      battery_pads:
        what: backlog/infused-kim/pads
        where:
          ref: matrix_inner_num
          shift: [22, 6.5]
        params:
          pads: 2
          net_1: BAT_RAW
          net_2: BAT_GND
          label_1: '+'
          label_2: '-'
      niceview:
        what: display_nice_view
        where: 
          ref: matrix_inner_num
          shift: [22.5,-10]
        params:
          VCC: VCC
          GND: GND
          CS: CS
          SCK: SCL
          MOSI: SDA
      slider:
        what: power_switch_smd_side 
        where: 
          ref: matrix_inner_bottom
          shift: [30.5,-0]
          rotate: -1
        params:
          side: B
          from: ON_P
          to: BAT_RAW
          invert_behavior: false
      battery:
        what: battery_connector_molex_pico_ezmate_1x02
        where: 
          ref: matrix_inner_num
          shift: [22.5,-2]
        params:
          side: B
          BAT_P: BAT_GND
          BAT_N: ON_P
          include_silkscreen: false
      battery_icon:
        what: backlog/infused-kim/icon_bat
        where:
          ref: matrix_inner_num
          shift: [22.5,3]
        params:
          side: B
      reset_switch:
        what: reset_switch_smd_side
        where: 
          ref: matrix_inner_bottom
          shift: [30, -10]
          rotate: -90
        params:
          include_bosses: true
          from: RST
          to: GND
          side: B
      left_text:
        what: utility_text
        where:
          ref: matrix_inner_bottom
          shift: [20,3]
        params:
          text: "Left Side"
          thickness: 1
          knockout: true
          width: 2
          height: 2    
      watermark:
        what: utility_text
        where:
          ref: matrix_inner_bottom
          shift: [20,-2]
        params:
          text: "Designed by imadam"
          thickness: 0
          width: 1
          height: 1    
      bottom_text:
        what: utility_text
        where:
          ref: thumbs_layer_cluster
          shift: [0,-6]
        params:
          mirrored: true
          side: B
          text: "Bottom"
          thickness: 1
          knockout: true
          width: 1.5
          height: 1.5
      reset_text:
        what: utility_text
        where:
          ref: matrix_inner_bottom
          shift: [23.5 , -10]
        params:
          mirrored: true
          side: B
          text: "← Reset"
          thickness: 1
          knockout: true
          width: 1
          height: 1
      power_text:
        what: utility_text
        where:
          ref: matrix_inner_bottom
          shift: [24.5, 0]
        params:
          mirrored: true
          side: B
          text: "← Power"
          thickness: 1
          knockout: true
          width: 1
          height: 1
      battery_text:
        what: utility_text
        where:
          ref: matrix_inner_num
          shift: [22.5, -7]
        params:
          mirrored: true
          side: B
          text: "Battery"
          thickness: 1
          knockout: true
          width: 1
          height: 1
      mcu_text:
        what: utility_text
        where:
          ref: matrix_inner_num
          shift: [22.5, -5]
          rotate: 90
        params:
          side: F
          text: "Controller"
          thickness: 1
          knockout: true
          width: 2
          height: 2
      encoder_text:
        what: utility_text
        where:
          ref: matrix_inner_home
          shift: [21.5, -3]
        params:
          side: F
          text: "Encoder"
          thickness: 1
          knockout: true
          width: 1.5
          height: 1.5
cases:



